### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by JoeTheBlow** [Alorel/lyrania-bot#1]
Does not work anymore after the latest chrome update, RIP. It will click "continue" but it will not click "attack" to actually start the fight. It will fight in dungeons but the "load" and "save" buttons do not appear anymore.

Broken on Chrome version 48.0.2535.0 dev-m (64-bit)

Works fine on Chrome Portable version 31.0.1650.57 m (old portable)

**Comment by Alorel** [comment]
@JoeTheBlow Sorry it took a while to reply. I'm afraid the game devs finally found out about the script and implemented countermeasures (see updated README). This repository is now only kept for reference until someone decides to contribute.
